<?php
$pageTitle = 'Tham Gia Tranh Tụng Bảo Vệ Quyền Lợi Đương Sự Trong Giai Đoạn Xét Xử Sơ Thẩm - TRUNG TÂM ĐÀO TẠO TƯ VẤN DOANH NGHIỆP BLT';
include '../includes/head.php';
?>

<?php include '../includes/header.php'; ?>

<div id="wrap_block_2">
  <?php
  include '../includes/navbar.php';
  ?>
</div>

<?php
$img = 'https://boiduongtuvanluat.com/img/luat-su-tranh-tung.jpg';
include '../includes/banner.php';
?>

<?php
$lever1 = 'Luật Sư Tranh Tụng';
$lever2 = 'Tham Gia Tranh Tụng Bảo Vệ Quyền Lợi Đương Sự Trong Giai Đoạn Xét Xử Sơ Thẩm';
include '../includes/breadcrumbs.php';
?>

<div id="wrap_block_article" class="wow fadeInUp">
  <div class="container">
    <div id="content_left" class="col-lg-9 col-xs-12" style="font-size: 20px;">
      <h2 class="text-center" style="color: red">THAM GIA TRANH TỤNG BẢO VỆ QUYỀN LỢI ĐƯƠNG SỰ TRONG GIAI ĐOẠN XÉT XỬ SƠ THẨM</h2>

      <br>

      <div><img src="https://boiduongtuvanluat.com/luat-su-tranh-tung/img/tham-gia-tranh-tung-bao-ve-quyen-loi-duong-su-trong-giai-doan-xet-xu-so-tham.jpg" alt="" style="width: 100%;"></div>

      <br>

      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">Tham gia tranh tụng bảo vệ quyền lợi đương sự trong giai đoạn x&eacute;t xử sơ thẩm</span></strong><span style="font-size:15px;line-height:115%;">&nbsp;l&agrave; một phần quan trọng trong quy tr&igrave;nh tố tụng d&acirc;n sự. Trong giai đoạn n&agrave;y, t&ograve;a &aacute;n sơ thẩm sẽ đưa ra quyết định về c&aacute;c tranh chấp giữa c&aacute;c b&ecirc;n tham gia vụ &aacute;n, v&agrave; việc bảo vệ quyền lợi hợp ph&aacute;p của đương sự (nguy&ecirc;n đơn, bị đơn hoặc người c&oacute; quyền lợi, nghĩa vụ li&ecirc;n quan) l&agrave; một yếu tố then chốt để đảm bảo c&ocirc;ng l&yacute; v&agrave; sự c&ocirc;ng bằng trong qu&aacute; tr&igrave;nh x&eacute;t xử.</span></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">1. Vai tr&ograve; của luật sư trong việc bảo vệ quyền lợi đương sự</span></strong></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">Trong giai đoạn x&eacute;t xử sơ thẩm, luật sư c&oacute; vai tr&ograve; rất quan trọng trong việc <strong>bảo vệ quyền lợi hợp ph&aacute;p của đương sự</strong>. Luật sư c&oacute; thể tham gia tranh tụng theo y&ecirc;u cầu của đương sự v&agrave; thực hiện một số nhiệm vụ cụ thể như:</span></p>
      <ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">Tư vấn ph&aacute;p l&yacute;</span></strong><span style="font-size:15px;line-height:115%;">: Luật sư sẽ cung cấp c&aacute;c th&ocirc;ng tin ph&aacute;p l&yacute;, gi&uacute;p đương sự hiểu r&otilde; c&aacute;c quyền v&agrave; nghĩa vụ của m&igrave;nh trong vụ &aacute;n.</span></li>
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">Soạn thảo đơn khởi kiện, đơn phản tố</span></strong><span style="font-size:15px;line-height:115%;">: Nếu đương sự l&agrave; nguy&ecirc;n đơn hoặc bị đơn, luật sư sẽ gi&uacute;p họ chuẩn bị v&agrave; nộp đơn khởi kiện hoặc phản tố để y&ecirc;u cầu t&ograve;a &aacute;n giải quyết tranh chấp.</span></li>
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">Chuẩn bị hồ sơ, t&agrave;i liệu v&agrave; chứng cứ</span></strong><span style="font-size:15px;line-height:115%;">: Luật sư sẽ gi&uacute;p đương sự chuẩn bị c&aacute;c t&agrave;i liệu, chứng cứ cần thiết để bảo vệ quan điểm của m&igrave;nh trong vụ &aacute;n. Việc thu thập v&agrave; tr&igrave;nh b&agrave;y chứng cứ l&agrave; rất quan trọng để t&ograve;a &aacute;n c&oacute; đủ cơ sở ra quyết định.</span></li>
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">Đại diện cho đương sự trong phi&ecirc;n t&ograve;a</span></strong><span style="font-size:15px;line-height:115%;">: Luật sư sẽ trực tiếp tham gia phi&ecirc;n t&ograve;a, tr&igrave;nh b&agrave;y l&yacute; lẽ bảo vệ quyền lợi của đương sự, đồng thời phản b&aacute;c lại c&aacute;c luận cứ của đối phương.</span></li>
      </ul>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">2. C&aacute;c bước tham gia tranh tụng trong giai đoạn x&eacute;t xử sơ thẩm</span></strong></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">Qu&aacute; tr&igrave;nh tham gia tranh tụng bảo vệ quyền lợi đương sự trong giai đoạn x&eacute;t xử sơ thẩm gồm một số bước quan trọng:</span></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">a. Chuẩn bị hồ sơ v&agrave; chứng cứ</span></strong></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">Trước khi phi&ecirc;n t&ograve;a diễn ra, luật sư cần phải chuẩn bị kỹ lưỡng hồ sơ v&agrave; chứng cứ để chứng minh quan điểm của đương sự. C&aacute;c bước bao gồm:</span></p>
      <ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">Thu thập chứng cứ</span></strong><span style="font-size:15px;line-height:115%;">: C&aacute;c chứng cứ c&oacute; thể l&agrave; t&agrave;i liệu, giấy tờ, lời khai của c&aacute;c nh&acirc;n chứng hoặc c&aacute;c chứng cứ kh&aacute;c c&oacute; li&ecirc;n quan đến vụ &aacute;n.</span></li>
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">Đặt ra c&aacute;c c&acirc;u hỏi cho nh&acirc;n chứng</span></strong><span style="font-size:15px;line-height:115%;">: Nếu c&oacute; nh&acirc;n chứng, luật sư cần chuẩn bị c&acirc;u hỏi cho họ, đồng thời x&aacute;c định r&otilde; những chứng cứ n&agrave;o sẽ được tr&igrave;nh b&agrave;y để hỗ trợ cho lập luận của đương sự.</span></li>
      </ul>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">b. Soạn thảo c&aacute;c văn bản tố tụng</span></strong></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">Luật sư soạn thảo v&agrave; nộp c&aacute;c văn bản tố tụng theo y&ecirc;u cầu của t&ograve;a &aacute;n hoặc ph&ugrave; hợp với quy định ph&aacute;p luật, bao gồm:</span></p>
      <ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">Đơn khởi kiện</span></strong><span style="font-size:15px;line-height:115%;">&nbsp;hoặc <strong>đơn phản tố</strong>: Luật sư sẽ soạn thảo đơn khởi kiện, phản tố để y&ecirc;u cầu t&ograve;a &aacute;n giải quyết tranh chấp giữa c&aacute;c b&ecirc;n.</span></li>
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">C&aacute;c t&agrave;i liệu bổ sung</span></strong><span style="font-size:15px;line-height:115%;">: Trong trường hợp cần thiết, luật sư cũng c&oacute; thể y&ecirc;u cầu bổ sung th&ecirc;m chứng cứ mới hoặc y&ecirc;u cầu t&ograve;a &aacute;n triệu tập nh&acirc;n chứng.</span></li>
      </ul>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">&nbsp;</span></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">c. Tham gia phi&ecirc;n t&ograve;a sơ thẩm</span></strong></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">Trong phi&ecirc;n t&ograve;a sơ thẩm, luật sư đ&oacute;ng vai tr&ograve; chủ chốt trong việc bảo vệ quyền lợi của đương sự th&ocirc;ng qua c&aacute;c hoạt động sau:</span></p>
      <ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">Tr&igrave;nh b&agrave;y luận điểm của đương sự</span></strong><span style="font-size:15px;line-height:115%;">: Luật sư sẽ tr&igrave;nh b&agrave;y c&aacute;c luận cứ bảo vệ quyền lợi của đương sự, dựa tr&ecirc;n c&aacute;c chứng cứ v&agrave; quy định ph&aacute;p luật để thuyết phục t&ograve;a &aacute;n chấp nhận y&ecirc;u cầu của đương sự.</span></li>
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">Đặt c&acirc;u hỏi</span></strong><span style="font-size:15px;line-height:115%;">: Trong phi&ecirc;n t&ograve;a, luật sư c&oacute; thể đặt c&acirc;u hỏi đối với c&aacute;c nh&acirc;n chứng hoặc đối phương để l&agrave;m r&otilde; c&aacute;c t&igrave;nh tiết vụ &aacute;n, hoặc phản b&aacute;c lại c&aacute;c luận điểm m&agrave; đối phương đưa ra.</span></li>
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">Phản b&aacute;c &yacute; kiến đối phương</span></strong><span style="font-size:15px;line-height:115%;">: Nếu đối phương đưa ra lập luận hoặc chứng cứ bất lợi cho đương sự, luật sư sẽ phải phản b&aacute;c v&agrave; đưa ra c&aacute;c chứng cứ chứng minh sự kh&ocirc;ng đ&uacute;ng của lập luận đ&oacute;.</span></li>
      </ul>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">d. Đảm bảo quyền lợi hợp ph&aacute;p của đương sự</span></strong></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">Luật sư sẽ bảo vệ quyền lợi hợp ph&aacute;p của đương sự trong suốt qu&aacute; tr&igrave;nh x&eacute;t xử. Cụ thể:</span></p>
      <ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">Bảo vệ quyền tiếp cận th&ocirc;ng tin</span></strong><span style="font-size:15px;line-height:115%;">: Đảm bảo rằng đương sự c&oacute; quyền tiếp cận v&agrave; xem x&eacute;t tất cả c&aacute;c t&agrave;i liệu, chứng cứ c&oacute; li&ecirc;n quan m&agrave; t&ograve;a &aacute;n hoặc đối phương đưa ra.</span></li>
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">Bảo vệ quyền b&igrave;nh đẳng trong tố tụng</span></strong><span style="font-size:15px;line-height:115%;">: Đảm bảo rằng đương sự kh&ocirc;ng bị đối xử bất c&ocirc;ng trong qu&aacute; tr&igrave;nh x&eacute;t xử, đặc biệt l&agrave; trong việc tiếp cận chứng cứ v&agrave; tham gia tranh tụng.</span></li>
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">Đảm bảo quyền y&ecirc;u cầu x&eacute;t xử c&ocirc;ng bằng</span></strong><span style="font-size:15px;line-height:115%;">: Luật sư sẽ y&ecirc;u cầu t&ograve;a &aacute;n tu&acirc;n thủ đ&uacute;ng quy tr&igrave;nh tố tụng, đảm bảo quyền lợi của đương sự kh&ocirc;ng bị x&acirc;m phạm.</span></li>
      </ul>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">3. Tham gia tranh tụng về c&aacute;c vấn đề ph&aacute;p l&yacute; trong vụ &aacute;n</span></strong></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">Trong giai đoạn x&eacute;t xử sơ thẩm, một phần quan trọng của việc bảo vệ quyền lợi hợp ph&aacute;p của đương sự l&agrave; tranh tụng về c&aacute;c vấn đề ph&aacute;p l&yacute; li&ecirc;n quan đến vụ &aacute;n:</span></p>
      <ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">Tranh tụng về &aacute;p dụng ph&aacute;p luật</span></strong><span style="font-size:15px;line-height:115%;">: Luật sư sẽ đưa ra c&aacute;c lập luận để đảm bảo rằng c&aacute;c quy định ph&aacute;p luật được &aacute;p dụng đ&uacute;ng đắn v&agrave; ph&ugrave; hợp với ho&agrave;n cảnh của vụ &aacute;n.</span></li>
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">Tranh tụng về sự thật của vụ &aacute;n</span></strong><span style="font-size:15px;line-height:115%;">: Nếu c&oacute; sự m&acirc;u thuẫn về sự thật giữa c&aacute;c b&ecirc;n, luật sư sẽ đưa ra chứng cứ v&agrave; lập luận để chứng minh quan điểm của đương sự l&agrave; đ&uacute;ng đắn.</span></li>
      </ul>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">4. Bảo vệ quyền lợi hợp ph&aacute;p của đương sự khi c&oacute; y&ecirc;u cầu về &aacute;p dụng biện ph&aacute;p khẩn cấp tạm thời</span></strong></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">Trong một số trường hợp, đương sự c&oacute; thể y&ecirc;u cầu t&ograve;a &aacute;n &aacute;p dụng biện ph&aacute;p khẩn cấp tạm thời để bảo vệ quyền lợi của m&igrave;nh trong qu&aacute; tr&igrave;nh x&eacute;t xử. Luật sư sẽ tham gia tranh tụng v&agrave; y&ecirc;u cầu t&ograve;a &aacute;n &aacute;p dụng biện ph&aacute;p như:</span></p>
      <ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">Cấm thay đổi t&igrave;nh trạng t&agrave;i sản</span></strong><span style="font-size:15px;line-height:115%;">: Y&ecirc;u cầu t&ograve;a &aacute;n ra quyết định cấm b&ecirc;n kia b&aacute;n, chuyển nhượng t&agrave;i sản trong suốt qu&aacute; tr&igrave;nh x&eacute;t xử.</span></li>
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">Tạm ho&atilde;n nghĩa vụ thi h&agrave;nh &aacute;n</span></strong><span style="font-size:15px;line-height:115%;">: Y&ecirc;u cầu t&ograve;a &aacute;n tạm ho&atilde;n việc thực hiện nghĩa vụ đối với b&ecirc;n thua kiện trong khi đang chờ quyết định cuối c&ugrave;ng của vụ &aacute;n.</span></li>
      </ul>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">5. C&aacute;c biện ph&aacute;p kh&aacute;c để bảo vệ quyền lợi đương sự</span></strong></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">Ngo&agrave;i c&aacute;c thủ tục ch&iacute;nh thức, luật sư c&ograve;n c&oacute; thể thực hiện một số biện ph&aacute;p kh&aacute;c để bảo vệ quyền lợi của đương sự trong giai đoạn sơ thẩm:</span></p>
      <ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">Đ&agrave;m ph&aacute;n, h&ograve;a giải</span></strong><span style="font-size:15px;line-height:115%;">: Trước hoặc trong qu&aacute; tr&igrave;nh x&eacute;t xử, luật sư c&oacute; thể tham gia đ&agrave;m ph&aacute;n, h&ograve;a giải giữa c&aacute;c b&ecirc;n để đạt được thỏa thuận giải quyết tranh chấp m&agrave; kh&ocirc;ng cần đến một bản &aacute;n của t&ograve;a &aacute;n.</span></li>
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">Khiếu nại h&agrave;nh vi tố tụng sai</span></strong><span style="font-size:15px;line-height:115%;">: Nếu trong qu&aacute; tr&igrave;nh x&eacute;t xử c&oacute; h&agrave;nh vi tố tụng sai, luật sư c&oacute; thể y&ecirc;u cầu t&ograve;a &aacute;n cấp cao xem x&eacute;t lại hoặc khiếu nại l&ecirc;n cơ quan c&oacute; thẩm quyền để bảo vệ quyền lợi của đương sự.</span></li>
      </ul>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">Kết luận</span></strong></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">Tham gia tranh tụng bảo vệ quyền lợi đương sự trong giai đoạn x&eacute;t xử sơ thẩm</span></strong><span style="font-size:15px;line-height:115%;">&nbsp;l&agrave; một nhiệm vụ rất quan trọng của luật sư trong quy tr&igrave;nh tố tụng d&acirc;n sự. Việc bảo vệ quyền lợi hợp ph&aacute;p của đương sự kh&ocirc;ng chỉ diễn ra trong phi&ecirc;n t&ograve;a m&agrave; c&ograve;n bao gồm việc chuẩn bị hồ sơ, chứng cứ, soạn thảo c&aacute;c văn bản tố tụng v&agrave; tham gia v&agrave;o c&aacute;c giai đoạn tố tụng kh&aacute;c. Luật sư phải nỗ lực hết m&igrave;nh để đảm bảo c&ocirc;ng l&yacute; v&agrave; quyền lợi của đương sự được bảo vệ đầy đủ v&agrave; đ&uacute;ng đắn theo quy định của ph&aacute;p luật.</span></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">------</span></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">TRUNG T&Acirc;M Đ&Agrave;O TẠO TƯ VẤN DOANH NGHIỆP BLT</span></strong></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:15px;line-height:115%;font-family:"Segoe UI Emoji",sans-serif;'>🏠</span><span style="font-size:15px;line-height:115%;">&nbsp;Số 3A đường Đồng Nai, Phường 2, Quận T&acirc;n B&igrave;nh, Th&agrave;nh phố Hồ Ch&iacute; Minh, Việt Nam</span></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:15px;line-height:115%;font-family:"Segoe UI Emoji",sans-serif;'>📱</span><span style="font-size:15px;line-height:115%;">&nbsp;079.72.99078</span></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:15px;line-height:115%;font-family:"Segoe UI Symbol",sans-serif;'>✉</span><span style="font-size:15px;line-height:115%;">&nbsp;</span><a href="mailto:lawtrainingcourses@gmail.com"><span style="font-size:15px;line-height:115%;">lawtrainingcourses@gmail.com</span></a></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:15px;line-height:115%;font-family:"Segoe UI Emoji",sans-serif;'>🌐</span><span style="font-size:15px;line-height:115%;">&nbsp;</span><a href="https://boiduongtuvanluat.com/"><span style="font-size:15px;line-height:115%;">https://boiduongtuvanluat.com/</span></a></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'>&nbsp;</p>


      <br>

      <?php include '../includes/support.php'; ?>
    </div>
    <div id="content_right" class="kmt_orange kmt_border col-sticky col-lg-3 col-xs-12">
      <?php include '../includes/news.php'; ?>
    </div>
  </div>
</div>

<?php
include '../includes/footer.php';
?>