<?php
$pageTitle = 'Thủ Tục Thụ Lý Vụ Án Hành Chính Theo Quy Định Pháp Luật Hiện Hành - TRUNG TÂM ĐÀO TẠO TƯ VẤN DOANH NGHIỆP BLT';
include '../includes/head.php';
?>

<?php include '../includes/header.php'; ?>

<div id="wrap_block_2">
  <?php
  include '../includes/navbar.php';
  ?>
</div>

<?php
$img = 'https://boiduongtuvanluat.com/img/luat-su-tranh-tung.jpg';
include '../includes/banner.php';
?>

<?php
$lever1 = 'Luật Sư Tranh Tụng';
$lever2 = 'Thủ Tục Thụ Lý Vụ Án Hành Chính Theo Quy Định Pháp Luật Hiện Hành';
include '../includes/breadcrumbs.php';
?>

<div id="wrap_block_article" class="wow fadeInUp">
  <div class="container">
    <div id="content_left" class="col-lg-9 col-xs-12" style="font-size: 20px;">
      <h2 class="text-center" style="color: red">THỦ TỤC THỤ LÝ VỤ ÁN HÀNH CHÍNH THEO QUY ĐỊNH PHÁP LUẬT HIỆN HÀNH</h2>

      <br>

      <div><img src="https://boiduongtuvanluat.com/luat-su-tranh-tung/img/thu-tuc-thu-ly-vu-an-hanh-chinh-theo-quy-dinh-phap-luat-hien-hanh.jpg" alt="" style="width: 100%;"></div>

      <br>

      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">Thủ tục thụ l&yacute; vụ &aacute;n h&agrave;nh ch&iacute;nh</span></strong><span style="font-size:15px;line-height:115%;">&nbsp;l&agrave; một qu&aacute; tr&igrave;nh trong hệ thống tố tụng h&agrave;nh ch&iacute;nh, theo đ&oacute; c&aacute;c cơ quan tố tụng (t&ograve;a &aacute;n) tiếp nhận v&agrave; xem x&eacute;t c&aacute;c y&ecirc;u cầu khởi kiện về h&agrave;nh vi h&agrave;nh ch&iacute;nh, quyết định h&agrave;nh ch&iacute;nh, văn bản quy phạm ph&aacute;p luật hoặc c&aacute;c vấn đề h&agrave;nh ch&iacute;nh kh&aacute;c li&ecirc;n quan đến quyền v&agrave; lợi &iacute;ch hợp ph&aacute;p của c&aacute; nh&acirc;n, tổ chức.</span></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">Ở Việt Nam, thủ tục thụ l&yacute; vụ &aacute;n h&agrave;nh ch&iacute;nh được quy định tại <strong>Luật Tố tụng h&agrave;nh ch&iacute;nh 2015</strong>, sửa đổi, bổ sung năm 2020. Dưới đ&acirc;y l&agrave; c&aacute;c bước v&agrave; quy định cụ thể về thủ tục thụ l&yacute; vụ &aacute;n h&agrave;nh ch&iacute;nh theo ph&aacute;p luật hiện h&agrave;nh.</span></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">1. Kh&aacute;i niệm vụ &aacute;n h&agrave;nh ch&iacute;nh</span></strong></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">Vụ &aacute;n h&agrave;nh ch&iacute;nh l&agrave; vụ &aacute;n m&agrave; trong đ&oacute; một b&ecirc;n l&agrave; cơ quan nh&agrave; nước, tổ chức, c&aacute; nh&acirc;n c&oacute; thẩm quyền thực hiện h&agrave;nh vi h&agrave;nh ch&iacute;nh hoặc quyết định h&agrave;nh ch&iacute;nh, văn bản quy phạm ph&aacute;p luật bị khởi kiện, y&ecirc;u cầu t&ograve;a &aacute;n giải quyết. C&aacute;c đối tượng n&agrave;y bao gồm h&agrave;nh vi h&agrave;nh ch&iacute;nh, quyết định h&agrave;nh ch&iacute;nh, hoặc h&agrave;nh vi kh&ocirc;ng thực hiện nghĩa vụ của cơ quan nh&agrave; nước đối với c&aacute; nh&acirc;n, tổ chức.</span></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">2. Điều kiện thụ l&yacute; vụ &aacute;n h&agrave;nh ch&iacute;nh</span></strong></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">Theo Điều 117 <strong>Luật Tố tụng h&agrave;nh ch&iacute;nh</strong>, để vụ &aacute;n h&agrave;nh ch&iacute;nh được thụ l&yacute;, cần đ&aacute;p ứng c&aacute;c điều kiện sau:</span></p>
      <ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">Đơn khởi kiện hợp lệ</span></strong><span style="font-size:15px;line-height:115%;">: Người khởi kiện phải nộp đơn khởi kiện ph&ugrave; hợp với c&aacute;c y&ecirc;u cầu về nội dung, h&igrave;nh thức. Đơn khởi kiện phải ghi r&otilde; c&aacute;c th&ocirc;ng tin như t&ecirc;n, địa chỉ của người khởi kiện, người bị kiện, y&ecirc;u cầu khởi kiện, căn cứ ph&aacute;p l&yacute; v&agrave; sự kiện, t&igrave;nh huống xảy ra tranh chấp.</span></li>
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">Thời hiệu khởi kiện</span></strong><span style="font-size:15px;line-height:115%;">: Vụ &aacute;n h&agrave;nh ch&iacute;nh chỉ được thụ l&yacute; nếu y&ecirc;u cầu khởi kiện được gửi trong thời hạn quy định (th&ocirc;ng thường l&agrave; 1 năm kể từ ng&agrave;y biết được h&agrave;nh vi, quyết định h&agrave;nh ch&iacute;nh bị khiếu nại).</span></li>
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">Vụ &aacute;n thuộc thẩm quyền của t&ograve;a &aacute;n</span></strong><span style="font-size:15px;line-height:115%;">: T&ograve;a &aacute;n c&oacute; thẩm quyền thụ l&yacute; vụ &aacute;n h&agrave;nh ch&iacute;nh dựa tr&ecirc;n c&aacute;c y&ecirc;u cầu v&agrave; h&agrave;nh vi vi phạm h&agrave;nh ch&iacute;nh của cơ quan nh&agrave; nước hoặc quyết định h&agrave;nh ch&iacute;nh.</span></li>
      </ul>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">3. Quy tr&igrave;nh thụ l&yacute; vụ &aacute;n h&agrave;nh ch&iacute;nh</span></strong></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">Thủ tục thụ l&yacute; vụ &aacute;n h&agrave;nh ch&iacute;nh theo quy định của <strong>Luật Tố tụng h&agrave;nh ch&iacute;nh 2015</strong> gồm c&aacute;c bước ch&iacute;nh như sau:</span></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">Bước 1: Nộp đơn khởi kiện</span></strong></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">Người khởi kiện (c&aacute; nh&acirc;n, tổ chức) nộp đơn khởi kiện tại t&ograve;a &aacute;n c&oacute; thẩm quyền (t&ograve;a &aacute;n cấp huyện hoặc cấp tỉnh t&ugrave;y theo t&iacute;nh chất của vụ việc) trong thời gian luật định. Đơn khởi kiện cần c&oacute; đủ c&aacute;c th&ocirc;ng tin sau:</span></p>
      <ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">Th&ocirc;ng tin về người khởi kiện v&agrave; người bị kiện.</span></li>
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">Y&ecirc;u cầu cụ thể của người khởi kiện.</span></li>
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">C&aacute;c t&agrave;i liệu, chứng cứ k&egrave;m theo đơn để chứng minh y&ecirc;u cầu l&agrave; hợp l&yacute; v&agrave; c&oacute; căn cứ ph&aacute;p l&yacute;.</span></li>
      </ul>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">Bước 2: Tiếp nhận v&agrave; kiểm tra đơn khởi kiện</span></strong></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">Khi nhận được đơn khởi kiện, t&ograve;a &aacute;n sẽ kiểm tra t&iacute;nh hợp lệ của đơn:</span></p>
      <ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">Nếu đơn khởi kiện đầy đủ v&agrave; hợp lệ, t&ograve;a &aacute;n sẽ th&ocirc;ng b&aacute;o cho người khởi kiện về việc tiếp nhận v&agrave; thụ l&yacute; vụ &aacute;n.</span></li>
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">Nếu đơn kh&ocirc;ng hợp lệ, t&ograve;a &aacute;n c&oacute; thể y&ecirc;u cầu sửa đổi, bổ sung hoặc trả lại đơn trong trường hợp kh&ocirc;ng đủ điều kiện thụ l&yacute;. Thời gian trả lời cho người khởi kiện l&agrave; trong <strong>5 ng&agrave;y</strong> kể từ ng&agrave;y nhận đơn.</span></li>
      </ul>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">Bước 3: Ra quyết định thụ l&yacute; vụ &aacute;n</span></strong></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">Sau khi đơn khởi kiện hợp lệ, t&ograve;a &aacute;n sẽ ra <strong>quyết định thụ l&yacute; vụ &aacute;n</strong> h&agrave;nh ch&iacute;nh. Quyết định n&agrave;y sẽ x&aacute;c định r&otilde; nội dung vụ &aacute;n, thời gian x&eacute;t xử v&agrave; c&aacute;c bước tiếp theo trong qu&aacute; tr&igrave;nh giải quyết vụ &aacute;n.</span></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">Bước 4: Gửi th&ocirc;ng b&aacute;o về việc thụ l&yacute; vụ &aacute;n</span></strong></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">T&ograve;a &aacute;n sẽ gửi th&ocirc;ng b&aacute;o về việc thụ l&yacute; vụ &aacute;n đến c&aacute;c b&ecirc;n li&ecirc;n quan, bao gồm:</span></p>
      <ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">Người khởi kiện (để họ biết vụ &aacute;n đ&atilde; được thụ l&yacute; v&agrave; sẽ tiếp tục).</span></li>
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">Người bị kiện (cơ quan nh&agrave; nước hoặc tổ chức c&aacute; nh&acirc;n li&ecirc;n quan đến h&agrave;nh vi h&agrave;nh ch&iacute;nh bị khởi kiện).</span></li>
      </ul>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">Th&ocirc;ng b&aacute;o n&agrave;y cũng sẽ th&ocirc;ng b&aacute;o về quyền v&agrave; nghĩa vụ của c&aacute;c b&ecirc;n trong suốt qu&aacute; tr&igrave;nh x&eacute;t xử vụ &aacute;n.</span></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">Bước 5: T&ograve;a &aacute;n chuẩn bị x&eacute;t xử vụ &aacute;n</span></strong></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">Sau khi thụ l&yacute; vụ &aacute;n, t&ograve;a &aacute;n sẽ tiến h&agrave;nh c&aacute;c c&ocirc;ng việc chuẩn bị x&eacute;t xử, bao gồm:</span></p>
      <ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">X&aacute;c minh th&ocirc;ng tin, thu thập chứng cứ li&ecirc;n quan.</span></li>
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">Mời c&aacute;c b&ecirc;n tham gia phi&ecirc;n h&ograve;a giải (nếu c&oacute;).</span></li>
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">Tổ chức phi&ecirc;n t&ograve;a để x&eacute;t xử vụ &aacute;n nếu c&aacute;c b&ecirc;n kh&ocirc;ng thể h&ograve;a giải được.</span></li>
      </ul>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">Bước 6: X&eacute;t xử vụ &aacute;n h&agrave;nh ch&iacute;nh</span></strong></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">T&ograve;a &aacute;n sẽ tiến h&agrave;nh x&eacute;t xử c&ocirc;ng khai vụ &aacute;n h&agrave;nh ch&iacute;nh theo c&aacute;c quy định ph&aacute;p luật hiện h&agrave;nh. C&aacute;c b&ecirc;n sẽ tr&igrave;nh b&agrave;y l&yacute; lẽ, chứng cứ v&agrave; t&ograve;a &aacute;n sẽ ra quyết định cuối c&ugrave;ng về vụ &aacute;n, c&oacute; thể l&agrave; quyết định h&agrave;nh ch&iacute;nh, y&ecirc;u cầu sửa đổi h&agrave;nh vi hoặc c&ocirc;ng nhận hoặc b&aacute;c bỏ y&ecirc;u cầu của người khởi kiện.</span></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">4. Thời gian thụ l&yacute; v&agrave; giải quyết vụ &aacute;n h&agrave;nh ch&iacute;nh</span></strong></p>
      <ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">T&ograve;a &aacute;n phải đưa ra quyết định thụ l&yacute; vụ &aacute;n h&agrave;nh ch&iacute;nh trong <strong>5 ng&agrave;y</strong> kể từ ng&agrave;y nhận đơn khởi kiện hợp lệ.</span></li>
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">Thời gian giải quyết vụ &aacute;n h&agrave;nh ch&iacute;nh kh&ocirc;ng qu&aacute; <strong>6 th&aacute;ng</strong> kể từ ng&agrave;y thụ l&yacute;, trừ c&aacute;c trường hợp đặc biệt c&oacute; thể k&eacute;o d&agrave;i thời gian giải quyết.</span></li>
      </ul>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">5. Trường hợp kh&ocirc;ng thụ l&yacute; vụ &aacute;n h&agrave;nh ch&iacute;nh</span></strong></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">Theo Điều 118 <strong>Luật Tố tụng h&agrave;nh ch&iacute;nh</strong>, t&ograve;a &aacute;n c&oacute; thể từ chối thụ l&yacute; vụ &aacute;n h&agrave;nh ch&iacute;nh trong c&aacute;c trường hợp sau:</span></p>
      <ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">Vụ &aacute;n kh&ocirc;ng thuộc thẩm quyền giải quyết của t&ograve;a &aacute;n h&agrave;nh ch&iacute;nh.</span></li>
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">Đơn khởi kiện kh&ocirc;ng hợp lệ, kh&ocirc;ng c&oacute; căn cứ ph&aacute;p l&yacute; hoặc y&ecirc;u cầu kh&ocirc;ng ph&ugrave; hợp với quy định của ph&aacute;p luật.</span></li>
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">Đ&atilde; hết thời hiệu khởi kiện m&agrave; người khởi kiện kh&ocirc;ng c&oacute; l&yacute; do ch&iacute;nh đ&aacute;ng.</span></li>
      </ul>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">Kết luận:</span></strong></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">Thủ tục thụ l&yacute; vụ &aacute;n h&agrave;nh ch&iacute;nh bao gồm việc kiểm tra t&iacute;nh hợp lệ của đơn khởi kiện, ra quyết định thụ l&yacute;, th&ocirc;ng b&aacute;o cho c&aacute;c b&ecirc;n li&ecirc;n quan v&agrave; chuẩn bị x&eacute;t xử. Để đảm bảo quyền lợi hợp ph&aacute;p của m&igrave;nh, người khởi kiện cần nắm r&otilde; quy tr&igrave;nh v&agrave; thời gian thụ l&yacute; vụ &aacute;n h&agrave;nh ch&iacute;nh theo quy định ph&aacute;p luật hiện h&agrave;nh.</span></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style="font-size:15px;line-height:115%;">------</span></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style="font-size:15px;line-height:115%;">TRUNG T&Acirc;M Đ&Agrave;O TẠO TƯ VẤN DOANH NGHIỆP BLT</span></strong></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:15px;line-height:115%;font-family:"Segoe UI Emoji",sans-serif;'>🏠</span><span style="font-size:15px;line-height:115%;">&nbsp;Số 3A đường Đồng Nai, Phường 2, Quận T&acirc;n B&igrave;nh, Th&agrave;nh phố Hồ Ch&iacute; Minh, Việt Nam</span></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:15px;line-height:115%;font-family:"Segoe UI Emoji",sans-serif;'>📱</span><span style="font-size:15px;line-height:115%;">&nbsp;079.72.99078</span></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:15px;line-height:115%;font-family:"Segoe UI Symbol",sans-serif;'>✉</span><span style="font-size:15px;line-height:115%;">&nbsp;</span><a href="mailto:lawtrainingcourses@gmail.com"><span style="font-size:15px;line-height:115%;">lawtrainingcourses@gmail.com</span></a></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:15px;line-height:115%;font-family:"Segoe UI Emoji",sans-serif;'>🌐</span><span style="font-size:15px;line-height:115%;">&nbsp;</span><a href="https://boiduongtuvanluat.com/"><span style="font-size:15px;line-height:115%;">https://boiduongtuvanluat.com/</span></a></p>
      <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:16px;font-family:"Calibri",sans-serif;'>&nbsp;</p>

      <br>

      <?php include '../includes/support.php'; ?>
    </div>
    <div id="content_right" class="kmt_orange kmt_border col-sticky col-lg-3 col-xs-12">
      <?php include '../includes/news.php'; ?>
    </div>
  </div>
</div>

<?php
include '../includes/footer.php';
?>